# Generated by Django 5.0.4 on 2024-05-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('customers', '0002_alter_address_options_alter_city_options_and_more'),
        ('product', '0003_alter_cart_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['-created_date'], name='billing_bil_created_8ddbb9_idx'),
        ),
    ]
