# Generated by Django 5.0.4 on 2024-05-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-product_number']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['-product_number'], name='product_car_product_d45274_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['-created_date'], name='product_cat_created_d9444f_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created_date'], name='product_com_created_28168a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_date'], name='product_pro_created_8355c3_idx'),
        ),
    ]
