# Generated by Django 5.0.4 on 2024-05-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistantcook',
            options={'ordering': ['-birth_date']},
        ),
        migrations.AlterModelOptions(
            name='chef',
            options={'ordering': ['-birth_date']},
        ),
        migrations.AlterModelOptions(
            name='cooker',
            options={'ordering': ['-birth_date']},
        ),
        migrations.AddIndex(
            model_name='assistantcook',
            index=models.Index(fields=['-birth_date'], name='chefs_assis_birth_d_7c95a1_idx'),
        ),
        migrations.AddIndex(
            model_name='chef',
            index=models.Index(fields=['-birth_date'], name='chefs_chef_birth_d_e9bda1_idx'),
        ),
        migrations.AddIndex(
            model_name='cooker',
            index=models.Index(fields=['-birth_date'], name='chefs_cooke_birth_d_8231fb_idx'),
        ),
    ]
