# Generated by Django 5.0.4 on 2024-05-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ['-user_id']},
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['-created_date'], name='customers_a_created_3b27e3_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['-created_date'], name='customers_c_created_227498_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['-created_date'], name='customers_c_created_e3d8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='customers',
            index=models.Index(fields=['-user_id'], name='customers_c_user_id_26f7b5_idx'),
        ),
    ]
