# Generated by Django 5.0.4 on 2024-05-19 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakezone', '0003_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-rating']},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['-rate']},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-rating'], name='cakezone_pr_rating_a40b16_idx'),
        ),
        migrations.AddIndex(
            model_name='rate',
            index=models.Index(fields=['-rate'], name='cakezone_ra_rate_137ae3_idx'),
        ),
    ]
